# Configuration options for Release Please

# Branch protection settings
branches:
  protection:
    master:
      required_approving_review_count: 0
      enforce_admins: true
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration
          - lint

# Release type settings
release:
  defaultBranch: master
  label: release

# PR title template
templates:
  prTitleTemplate: "Release(${version})"

# Changelog configuration
changelog:
  labels:
    - 'feature'
    - 'fix'
    - 'chore'
  sections:
    - title: 'Features'
      labels:
        - 'feature'
    - title: 'Bug Fixes'
      labels:
        - 'fix'
    - title: 'Chores'
      labels:
        - 'chore'

# Versioning options
versioning:
  strategy: "conventional-commits"
  majorVersion: "2"

# Bump options
bump:
  strategy: "conventional-commits"
  majorVersion: "2"

