# Constants
SECRET_NAME  = 'IntelliTrader'
REGION_NAME  = 'ap-south-1'
EXCHANGE_NSE = 'NSE'
EXCHANGE_BSE = 'BSE'
SOURCE_PATH  = './src'
OUTPUT_PATH  = './src/output'
DATA_PATH    = './src/data'
ACCESS_TOKEN_PATH  = './src/output/access_token'
REQUEST_TOKEN_PATH = './src/output/request_token'
CONFIGURATION_PATH = './src/configuration'