name: Automatically create pull request

on:
  push:
    branches: 
        - develop

jobs:
  pull-request:
    name: Open PR to Master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: Get latest commit message
      id: latest_commit
      run: echo "::set-output name=message::$(git log --format=%B -n 1 HEAD)"

    - name: Determine PR Label
      id: determine_label
      run: |
        if [[ "${{ steps.latest_commit.outputs.message }}" == *"fix"* ]]; then
          echo "::set-output name=label::bug"
        else
          echo "::set-output name=label::enhancement"
        fi
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: ${{ steps.latest_commit.outputs.message }}
            committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
            author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
            signoff: false
            title: ${{ steps.latest_commit.outputs.message }}
            body: |
                - ${{ steps.latest_commit.outputs.message }}
                - Updated with *today's* date
                - Auto-generated by [create-pull-request]

            labels: ${{ steps.determine_label.outputs.label }}
            assignees: iamkrish-coder
            reviewers: iamkrish-coder          
            draft: false    

    # - uses: repo-sync/pull-request@v2
    #   name: pull-request
    #   id: create_pr
    #   with:
    #     destination_branch: "master"
    #     pr_title: ${{ steps.latest_commit.outputs.message }}
    #     pr_body: "*An automated PR*"
    #     pr_assignee: "iamkrish-coder"
    #     pr_label: ${{ steps.determine_label.outputs.label }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Merge Pull Request
    #   uses: juliangruber/merge-pull-request-action@v1
    #   with:
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       number: ${{ steps.create_pr.outputs.pr_number }}
    #       method: squash
