name: Create pull request
on:
  push:
    branches:
      - develop
jobs:
  PR_Develop_To_Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - name: Determine PR Label
        id: determine_label
        run: |
            if [[ "${{ steps.latest_commit.outputs.message }}" == *"fix"* ]]; then
              echo "::set-output name=label::bug"
            else
              echo "::set-output name=label::enhancement"
            fi
      - name: Reset release branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update release branch
          title: Update release branch
          branch: feature-release
          labels: ${{ steps.determine_label.outputs.label }}
          delete-branch: true
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          assignees: iamkrish-coder
          reviewers: iamkrish-coder