name: Create pull request
on:
  push:
    branches:
      - develop
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: feature-build
          delete-branch: true
          labels: |
            enhancement
            automated pull request
          assignees: iamkrish-coder
          reviewers: iamkrish-coder
          draft: false
