name: Auto Issues
on:
  push:
    branches:
      - develop

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"
    
      - name: Create issue based on commit message
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/feature_request.md
          title: 'Feature Request'
          assignees: iamkrish-coder
          labels: 'enhancement'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

