name: Automatically create / update pull request / merge

on:
  push:
    branches: [ develop ]

jobs:
  create_or_update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code

      - name: Get Latest Commit Message
        id: get_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 HEAD)"

      - uses: peter-evans/create-pull-request@v5  # Action to create/update PR
        name: Create or Update Pull Request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.get_message.outputs.message }}
          branch: develop  # Branch to compare with Master
          base: master     # Target branch (Master)
          title: ${{ steps.get_message.outputs.message }}  # PR title uses commit message
          body: |-  # Optional PR body message
            An automated PR created from develop branch push.

          labels: bug, enhancement  # Desired labels for the PR
          # You can add more labels here separated by commas

          # Optional: Update existing PR instead of creating a new one
          update: true 
          delete-branch: false  # Optional: Don't delete the develop branch after PR


          github_token: ${{ secrets.GITHUB_TOKEN }}
