name: Auto Merge to Master

on:
  push:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const compare = await github.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: 'master',
            head: 'develop',
          });

          if (compare.data.status === 'identical') {
            console.log('No changes between develop and master.');
          } else {
            console.log('Creating Pull Request...');
            const pr = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Auto-Merge from Develop to Master',
              head: 'develop',
              base: 'master',
              body: 'This pull request is automatically generated by GitHub Actions.',
            });
            console.log(`Pull Request created: ${pr.data.html_url}`);
          }
