name: Auto Pull Request
on:
  push:
    branches:
      - develop

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Check for existing open PR
        id: check_pr
        run: |
          API_URL="https://api.github.com"
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.repository }}
          SHA=${{ github.sha }}
          OPEN_PR=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$API_URL/repos/$OWNER/$REPO/pulls?head=$OWNER:$SHA&state=open" | jq '.[0].number')
          echo "::set-output name=open_pr::$OPEN_PR"

      - name: Get latest commit message
        id: latest_commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1 HEAD)"

      - name: Update existing PR and add latest commit
        if: steps.check_pr.outputs.open_pr
        run: |
          API_URL="https://api.github.com"
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.repository }}
          PR_NUMBER=${{ steps.check_pr.outputs.open_pr }}
          LATEST_COMMIT_MSG="${{ steps.latest_commit.outputs.message }}"
          
          # Update pull request title
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "$API_URL/repos/$OWNER/$REPO/pulls/$PR_NUMBER" -d "{\"title\":\"$LATEST_COMMIT_MSG\"}"
          
          # Add latest commit to pull request
          git push "https://github.com/$OWNER/$REPO.git" HEAD:refs/heads/feature-build --force-with-lease

      - name: Create Pull Request (if no open PR exists)
        if: steps.check_pr.outputs.open_pr == null
        uses: peter-evans/create-pull-request@v5
        with:
          branch: feature-build
          title: ${{ steps.latest_commit.outputs.message }} 
          body: |
            Updates to IntelliTrader
            - Srikrishnan
            - Auto-generated Pull Request on push to Develop
          delete-branch: true
          labels: |
            enhancement
            automated pull request
          assignees: iamkrish-coder
          draft: false
