name: Auto Pull Request and Update

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  dummy_job:
    name: 'Dummy Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Dummy Step'
        run: echo "This is a dummy job, it doesn't do anything."

  create_pr:
    name: 'Create PR'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'Create PR'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo } = context.repo;
            const pulls = await github.rest.pulls.list({
              owner: 'iamkrish-coder',
              repo: repo,
              head: context.ref,
              base: 'main',
              state: 'open',
            });
            
            if (pulls.data.length < 1) {
              await github.rest.pulls.create({
                title: '[CI] Merge branch into main',
                owner: 'iamkrish-coder',
                repo: ${{ github.repository }},
                head: context.ref,
                base: 'main',
                body: [
                  'This PR is auto-generated by',
                  '[actions/github-script](https://github.com/actions/github-script)',
                ].join('\n'),
                labels: ['enhancement', 'automated pull request'],
                assignees: ['iamkrish-coder'],
                draft: false,
              });
            } else {
              const existingPR = pulls.data[0];
              await github.rest.pulls.update({
                owner: 'iamkrish-coder',
                repo: ${{ github.repository }},
                pull_number: existingPR.number,
                body: [
                  existingPR.body,
                  `Updated by Job ${context.job}`,
                ].join('\n'),
              });
            }
