name: CI - Build, Test and Create Pull Request

on:
  push:
    branches:
      - develop  # Trigger on push to develop branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          python -m unittest discover  # Run unit tests using unittest

      - name: Create Pull Request (if tests pass)
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automatic PR from develop - ${{ github.sha }}'
          body: |
            Built and tested changes from the develop branch.

            **Test results:**
            [Insert link to test report here (optional)]  # Link to test report if applicable
          branch: develop
          base: master
          token: ${{ secrets.GITHUB_TOKEN }}
