name: Auto Merge

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: Yproximite/auto-approve-and-merge-dependabot-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}