const { Octokit } = require('@octokit/rest');

async function run() {
  const octokit = new Octokit({
    auth: process.env.GITHUB_TOKEN,
  });

  const compare = await octokit.repos.compareCommits({
    owner: process.env.GITHUB_REPOSITORY_OWNER,
    repo: process.env.GITHUB_REPOSITORY,
    base: 'master',
    head: 'develop',
  });

  if (compare.data.status === 'identical') {
    console.log('No changes between develop and master.');
  } else {
    console.log('Creating Pull Request...');
    const pr = await octokit.pulls.create({
      owner: process.env.GITHUB_REPOSITORY_OWNER,
      repo: process.env.GITHUB_REPOSITORY,
      title: 'Auto-Merge from Develop to Master',
      head: 'develop',
      base: 'master',
      body: 'This pull request is automatically generated by GitHub Actions.',
    });
    console.log(`Pull Request created: ${pr.data.html_url}`);
  }
}

run();
