name: Create pull request
on:
  push:
    branches:
      - develop
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: feature-build
          delete-branch: true
          labels: |
            enhancement
            automated pull request
          assignees: iamkrish-coder
          reviewers: iamkrish-coder
          draft: false
      - name: Create or Update Project Card
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: IntelliTrader
          column-name: Done
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}