name: Automatically Create Pull Requests
on:
  push:
    branches:
    - develop 

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "master"                      # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
        pr_body: |                                        # Full markdown support, requires pr_title to be set
          :crown: *An automated PR*

        pr_assignee: "iamkrish-coder"                       # Comma-separated list (no spaces)
        pr_label: "automerge"                               # Comma-separated list (no spaces)
        pr_milestone: ""                                    # Milestone name no Required it is comment
        pr_draft: false                                     # Creates pull request as draft
        pr_allow_empty: false                               # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}           # If blank, default: secrets.GITHUB_TOKEN