name: Auto Merge to Master

on:
  push:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install @actions/github

    - name: Create Pull Request
      run: |
        const github = require('@actions/github');
        const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

        const compare = await octokit.repos.compareCommits({
          owner: process.env.GITHUB_REPOSITORY_OWNER,
          repo: process.env.GITHUB_REPOSITORY,
          base: 'master',
          head: 'develop',
        });

        if (compare.data.status === 'identical') {
          console.log('No changes between develop and master.');
        } else {
          console.log('Creating Pull Request...');
          const pr = await octokit.pulls.create({
            owner: process.env.GITHUB_REPOSITORY_OWNER,
            repo: process.env.GITHUB_REPOSITORY,
            title: 'Auto-Merge from Develop to Master',
            head: 'develop',
            base: 'master',
            body: 'This pull request is automatically generated by GitHub Actions.',
          });
          console.log(`Pull Request created: ${pr.data.html_url}`);
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
