name: Auto Pull Request
on:
  push:
    branches:
      - develop

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Check for existing open PR
        id: check_pr
        run: |
          API_URL="https://api.github.com"
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.repository }}
          SHA=${{ github.sha }}
          OPEN_PR=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$API_URL/repos/$OWNER/$REPO/pulls?head=$OWNER:$SHA&state=open" | jq -r '.[0].number')
          echo "::set-output name=open_pr::$OPEN_PR"

      - name: Get latest commit message
        id: latest_commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1 HEAD)"

      - name: Update existing PR or create new PR
        id: update_or_create_pr
        run: |
          LATEST_COMMIT_MSG="${{ steps.latest_commit.outputs.message }}"
          if [ -n "${{ steps.check_pr.outputs.open_pr }}" ]; then
            API_URL="https://api.github.com"
            OWNER=${{ github.repository_owner }}
            REPO=${{ github.repository }}
            PR_NUMBER=${{ steps.check_pr.outputs.open_pr }}
            
            # Update pull request title
            curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "$API_URL/repos/$OWNER/$REPO/pulls/$PR_NUMBER" -d "{\"title\":\"$LATEST_COMMIT_MSG\"}"
            
            # Add latest commit to pull request
            git push "https://github.com/$OWNER/$REPO.git" HEAD:refs/heads/feature-build --force-with-lease
          else
            # Create new pull request
            echo "Creating new pull request"
            # You can adjust the body of the PR as needed
            TITLE="$LATEST_COMMIT_MSG"
            BODY="Updates to IntelliTrader\n- Srikrishnan\n- Auto-generated Pull Request on push to Develop"
            hub pull-request -b develop -h feature-build -m "$TITLE" -m "$BODY"
          fi

      - name: Set output for new PR URL
        if: steps.update_or_create_pr.outputs.open_pr == null
        run: |
          echo "::set-output name=new_pr_url::$(jq -r '.html_url' <<< "${{ steps.update_or_create_pr.outputs.stdout }}")"
