name: Auto Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    - name: Auto Release
      uses: google-github-actions/release-please-action@v4
      id: create_pr
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: simple
        target-branch: master
        release-notes-generator: "conventional"