name: hourly-sync-master

on:
  push:
    branches:
      - develop

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in develop branch
        run: |
          git fetch origin develop
          git diff --quiet origin/develop release
          if [ $? -eq 0 ]; then
            echo "No changes found in develop branch. Skipping PR creation."
            exit 0
          fi

      - name: Create Pull Request (if changes found)
        run: |
          gh pr create -f origin/develop -t release --title 'Merge develop into release' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
