name: Automatically Merge Pull Requests
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  status: {}
env:
    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    MERGE_LABELS: "automerge"
    MERGE_REMOVE_LABELS: "automerge"
    MERGE_METHOD: "rebase"
    MERGE_COMMIT_MESSAGE: "pull-request-title"
    MERGE_FORKS: "false"
    MERGE_RETRIES: "6"
    MERGE_RETRY_SLEEP: "10000"
    MERGE_REQUIRED_APPROVALS: "0"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
