name: Auto Approve PR

on:
  pull_request:
    types:
      - opened

jobs:
  auto_approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Approve PR
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" \
            -d '{"event": "APPROVE"}'
