name: Pull Request Automation

on:
  push:
    branches:
      - develop

jobs:
  auto-create:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Existing Pull Request
      id: pr_check
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prList = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: 'develop',
            base: 'master',
          });

          core.setOutput('pr_exists', prList.data.length > 0);

    - name: Create Pull Request
      if: steps.pr_check.outputs.pr_exists != 'true'
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = 'Automated Merge from develop to master';
          const body = 'This is an automated pull request.';
          const head = 'develop';
          const base = 'master';

          const pr = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title,
            body,
            head,
            base,
          });

          // Assign the pull request to the repository owner (self)
          await github.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.data.number,
            assignees: [context.repo.owner],
          });

          // Request the repository owner as a reviewer
          await github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.data.number,
            review_requesters: [context.repo.owner],
          });

          core.setOutput('pull_request_number', pr.data.number);
  
  auto-generate:
    needs: auto-create
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Configure Git
      run: |
        git config user.name "Srikrishnan"
        git config user.email "krishnan.sri92@gmail.com"

    - name: Generate Changelog
      run: npx standard-version --skip.changelog

    - name: Request Review
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            const { context, github } = require('@actions/github');
            const prNumber = context.payload.workflow_run.conclusion === 'success' 
                ? context.workflow_run.outputs.pull_request_number 
                : null;

            if (prNumber) {
                await github.pulls.createReviewRequest({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                reviewers: ['iamkrish-coder'],
                });
            }


