name: Release on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  release-on-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release Please
      uses: release-please/action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
