name: Release Tags Automation

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Git tag (for automatic releases)
        automatic_release_tag: v1.0.0 # specify your tag or let it be generated automatically
        # Should this release be marked as a draft?
        draft: false # optional
        # Should this release be marked as a pre-release?
        prerelease: true # optional, default is true
        # Release title (for automatic releases)
        title: Release v1.0.0 # optional
