name: Release Tags Automation

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - name: "Get current version"
        id: get_version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: "Increment version"
        id: increment_version
        uses: marvinpinto/semver@v0.2.0
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          release_type: 'preminor'
          bump_pre: true

      - name: "Set new version"
        run: |
          echo "VERSION=${{ steps.increment_version.outputs.VERSION }}" >> $GITHUB_ENV

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.increment_version.outputs.VERSION }}"
          prerelease: true
          title: "Development Build"

  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
