name: Release Tags Automation

on:
  push:
    branches:
      - master

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and semver
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm
        npm install semver

    - name: Get latest tag
      id: get_tag
      run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"

    - name: Increment version
      id: version
      run: |
        echo "::set-output name=NEW_VERSION::$(node -p 'const semver = require("semver"); const currentVersion = process.env.TAG || "0.0.0"; console.log(semver.inc(currentVersion, "patch"));')"

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: v${{ steps.version.outputs.NEW_VERSION }}
        draft: false
        prerelease: true
        title: Release v${{ steps.version.outputs.NEW_VERSION }}
