on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  tag-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Tag Master
        uses: nionata/EzReleases@vX.X
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
